### ISSUE TITLE
HealPix pixel area units

### ISSUE THREAD

**Issue by NiallMac** [esheldon/healpix_util#2]
Looks like the units for the reported pixel area are off - see the example below. The area reported in square degrees should actually be square radians.

```
In [87]: hpix
Out[87]: 
scheme:       1
scheme_name:  RING
nside:        1024
npix:         12582912
ncap:         2095104
area:         9.98685e-07 square degrees
area:         0.00359527 square arcmin
area:         12.943 square arcsec

In [88]: 4*pi/hpix.npix
Out[88]: 9.986854087797142e-07
```

**Comment by esheldon** [comment]
I've pushed a commit that I think fixes this. Please pull from git master and check.

**Comment by NiallMac** [comment]
That works, thanks Erin.
